
CREATE TABLE papeis(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
    );


CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    papel_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (papel_id) REFERENCES papeis(id) -- Define a FK
);
CREATE TABLE detalhes_usuario (
    usuario_id INT PRIMARY KEY,
    termo_imagem BOOLEAN,
    curso VARCHAR(255),
    instituicao VARCHAR(255),
    telefone VARCHAR(255),
    data_nascimento DATE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);


CREATE TABLE evento (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);
CREATE TABLE tipos(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
    );

CREATE TABLE locais(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
    );
ALTER TABLE locais
add column descricao VARCHAR(255) NOT NULL;

CREATE TABLE sala_locais(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    local_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (local_id) REFERENCES locais(id)
    );
CREATE TABLE convidado(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255),
    descricao VARCHAR(2000),
    formacao VARCHAR(255),
    instituicao VARCHAR(255),
    foto VARCHAR(255)
);
CREATE TABLE atividade (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL,
descricao VARCHAR(255) NOT NULL,
hora_inicio TIMESTAMP NOT NULL,
hora_fim TIMESTAMP NOT NULL,
tipo_id INT NOT NULL,
sala_id INT NOT NULL,
FOREIGN KEY (tipo_id) REFERENCES tipos(id),
FOREIGN KEY (sala_id) REFERENCES sala_locais(id)
);
CREATE TABLE atividade_convidado (
    id INT PRIMARY KEY AUTO_INCREMENT,
    atividade_id INT NOT NULL,
    convidado_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (atividade_id) REFERENCES atividade(id),
    FOREIGN KEY (convidado_id) REFERENCES convidado(id)
);
CREATE TABLE submissao (
 id INT PRIMARY KEY AUTO_INCREMENT,
 usuario_id INT NOT NULL,
 titulo VARCHAR(255) NOT NULL,
 resumo VARCHAR(2000) NOT NULL,
 autores VARCHAR(255),
artigo_url VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP NULL
);
CREATE TABLE patrocinadores (
id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  tipo_patrocinio VARCHAR(255),
  logo VARCHAR(255), -- Ajuste o tamanho conforme necessário
  edicao_evento INT,
  FOREIGN KEY (edicao_evento) REFERENCES evento(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
 );
ALTER TABLE convidado
ADD COLUMN created_at timestamp DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN deleted_at timestamp NULL DEFAULT NULL;

ALTER TABLE convidado
ADD COLUMN evento_id INT NOT NULL,
ADD CONSTRAINT fk_convidado_evento
FOREIGN KEY (evento_id)
REFERENCES evento(id);